"""Integration tests for GoogleCloudTTSProvider

These tests make real API calls to the google_tts service.
They will be skipped if GOOGLE_CLOUD_API_KEY is not set in environment.

Run with: pytest audio/test_google_tts.py -m live_api -v

Auto-generated by provider onboarding agent.
"""

import os
import pytest
from pathlib import Path
from core.providers.audio.google_tts import GoogleTTSProvider
from core.providers.base import AudioProviderConfig


# Skip all tests in this file if API key not available
pytestmark = pytest.mark.skipif(
    not os.getenv("GOOGLE_CLOUD_API_KEY"),
    reason="GOOGLE_CLOUD_API_KEY not set - skipping live API tests"
)


@pytest.fixture
def google_tts_config():
    """Create google_tts provider configuration"""
    api_key = os.getenv("GOOGLE_CLOUD_API_KEY")
    return AudioProviderConfig(
        api_key=api_key,
        timeout=60
    )


@pytest.fixture
def google_tts_provider(google_tts_config):
    """Create google_tts provider instance"""
    return GoogleTTSProvider(google_tts_config)


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_basic_generation(google_tts_provider):
    """Test basic text-to-speech generation with default settings"""
    result = await google_tts_provider.generate_speech(
        text="Hello world",
    )

    assert result is not None
    assert result.audio_data is not None
    assert len(result.audio_data) > 0


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_custom_voice(google_tts_provider):
    """Test text-to-speech generation with specific voice model"""
    result = await google_tts_provider.generate_speech(
        text="Testing custom voice",
        voice_name="en-US-Neural2-A",
    )

    assert result is not None
    assert result.audio_data is not None


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_audio_parameters(google_tts_provider):
    """Test generation with custom speaking rate, pitch, and volume"""
    result = await google_tts_provider.generate_speech(
        text="Testing audio parameters",
        speaking_rate=1.5,
        pitch=5.0,
        volume_gain_db=2.0,
    )

    assert result is not None
    assert result.audio_data is not None


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_list_voices(google_tts_provider):
    """Test retrieving available voices from the provider"""
    result = await google_tts_provider.list_voices(
    )

    assert result is not None
    assert result is not None
    assert len(result) > 0


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_list_voices_with_language_filter(google_tts_provider):
    """Test listing voices filtered by language code"""
    result = await google_tts_provider.list_voices(
        language_code="en-US",
    )

    assert result is not None
    assert result is not None


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_validate_credentials_success(google_tts_provider):
    """Test credential validation with valid API key"""
    result = await google_tts_provider.validate_credentials(
    )

    assert result == True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_validate_credentials_invalid_key(google_tts_provider):
    """Test credential validation with invalid API key"""
    result = await google_tts_provider.validate_credentials(
    )

    assert result == False


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_empty_text_error(google_tts_provider):
    """Test error handling when empty text is provided"""
    # This test expects an error
    try:
        result = await google_tts_provider.generate_speech(
            text="",
        )
        # If result exists, check it indicates failure
        if hasattr(result, "success"):
            assert result.success is False
    except Exception:
        pass  # Error is expected


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_none_text_error(google_tts_provider):
    """Test error handling when None is provided as text"""
    # This test expects an error
    try:
        result = await google_tts_provider.generate_speech(
            text=None,
        )
        # If result exists, check it indicates failure
        if hasattr(result, "success"):
            assert result.success is False
    except Exception:
        pass  # Error is expected


@pytest.mark.live_api
def test_invalid_speaking_rate(google_tts_provider):
    """Test that speaking rate is clamped to valid range"""
    result = google_tts_provider.__init__(
        speaking_rate=10.0,
    )



@pytest.mark.live_api
def test_invalid_pitch(google_tts_provider):
    """Test that pitch is clamped to valid range"""
    result = google_tts_provider.__init__(
        pitch=50.0,
    )



@pytest.mark.live_api
def test_invalid_volume_gain(google_tts_provider):
    """Test that volume gain is clamped to valid range"""
    result = google_tts_provider.__init__(
        volume_gain_db=100.0,
    )



@pytest.mark.live_api
@pytest.mark.asyncio
async def test_ssml_input(google_tts_provider):
    """Test text-to-speech generation with SSML markup"""
    result = await google_tts_provider.generate_speech(
        text="<speak>Hello <break time='500ms'/> world</speak>",
        is_ssml=True,
    )

    assert result is not None
    assert result.audio_data is not None


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_different_audio_encodings(google_tts_provider):
    """Test generation with different audio encoding formats"""
    result = await google_tts_provider.generate_speech(
        text="Testing audio format",
        audio_encoding="LINEAR16",
    )

    assert result is not None
    assert result.audio_data is not None


@pytest.mark.live_api
def test_provider_name(google_tts_provider):
    """Test that provider name is correctly set"""
    result = google_tts_provider.name(
    )



@pytest.mark.live_api
def test_api_key_from_env(google_tts_provider):
    """Test that API key can be loaded from environment variable"""
    result = google_tts_provider.__init__(
    )



@pytest.mark.live_api
@pytest.mark.asyncio
async def test_long_text_generation(google_tts_provider):
    """Test generation with longer text input"""
    result = await google_tts_provider.generate_speech(
        text="This is a longer text that should be synthesized properly. It contains multiple sentences and should test the provider's ability to handle more substantial content.",
    )

    assert result is not None
    assert result.audio_data is not None
    assert len(result.audio_data) > 0


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_effects_profile(google_tts_provider):
    """Test generation with audio effects profile"""
    result = await google_tts_provider.generate_speech(
        text="Testing audio effects",
        effects_profile_id=['telephony-class-application'],
    )

    assert result is not None
    assert result.audio_data is not None


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_custom_sample_rate(google_tts_provider):
    """Test generation with custom sample rate"""
    result = await google_tts_provider.generate_speech(
        text="Testing sample rate",
        sample_rate_hertz=24000,
    )

    assert result is not None
    assert result.audio_data is not None


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_multiple_languages(google_tts_provider):
    """Test generation with different language codes"""
    result = await google_tts_provider.generate_speech(
        text="Hola mundo",
        language_code="es-ES",
    )

    assert result is not None
    assert result.audio_data is not None

