"""Integration tests for ElevenLabsProvider

These tests make real API calls to the elevenlabs service.
They will be skipped if ELEVENLABS_API_KEY is not set in environment.

Run with: pytest audio/test_elevenlabs.py -m live_api -v

Auto-generated by provider onboarding agent.
"""

import os
import pytest
from pathlib import Path
from core.providers.audio.elevenlabs import ElevenLabsProvider
from core.providers.base import AudioProviderConfig


# Skip all tests in this file if API key not available
pytestmark = pytest.mark.skipif(
    not os.getenv("ELEVENLABS_API_KEY"),
    reason="ELEVENLABS_API_KEY not set - skipping live API tests"
)


@pytest.fixture
def elevenlabs_config():
    """Create elevenlabs provider configuration"""
    api_key = os.getenv("ELEVENLABS_API_KEY")
    return AudioProviderConfig(
        api_key=api_key,
        timeout=60
    )


@pytest.fixture
def elevenlabs_provider(elevenlabs_config):
    """Create elevenlabs provider instance"""
    return ElevenLabsProvider(elevenlabs_config)


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_basic_generation(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_voice_id(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_model(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_voice_settings(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_streaming(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_output_format(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_list_voices(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_validate_credentials_valid(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_validate_credentials_invalid(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_error_empty_text(elevenlabs_provider):
    """"""
    # This test expects an error
    try:
        result = await elevenlabs_provider.generate_speech(
        )
        # If result exists, check it indicates failure
        if hasattr(result, "success"):
            assert result.success is False
    except Exception:
        pass  # Error is expected


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_error_missing_api_key(elevenlabs_provider):
    """"""
    # This test expects an error
    try:
        result = await elevenlabs_provider.generate_speech(
        )
        # If result exists, check it indicates failure
        if hasattr(result, "success"):
            assert result.success is False
    except Exception:
        pass  # Error is expected


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_initialization_default(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_initialization_custom_model(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_initialization_with_voice_settings(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_get_headers(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_basic_generation(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_voice_id(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_model(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_voice_settings(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_basic_generation(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_voice_id(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_voice_settings(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_different_models(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_turbo_model(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_output_format(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_streaming(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_list_voices(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_validate_credentials(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_validate_credentials_invalid(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_empty_text_error(elevenlabs_provider):
    """"""
    # This test expects an error
    try:
        result = await elevenlabs_provider.generate_speech(
        )
        # If result exists, check it indicates failure
        if hasattr(result, "success"):
            assert result.success is False
    except Exception:
        pass  # Error is expected


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_missing_api_key_error(elevenlabs_provider):
    """"""
    # This test expects an error
    try:
        result = await elevenlabs_provider.generate_speech(
        )
        # If result exists, check it indicates failure
        if hasattr(result, "success"):
            assert result.success is False
    except Exception:
        pass  # Error is expected


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_invalid_voice_id_error(elevenlabs_provider):
    """"""
    # This test expects an error
    try:
        result = await elevenlabs_provider.generate_speech(
        )
        # If result exists, check it indicates failure
        if hasattr(result, "success"):
            assert result.success is False
    except Exception:
        pass  # Error is expected


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_provider_name(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_initialization_with_defaults(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_initialization_with_voice_settings(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_long_text_generation(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_basic_generation(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_voice_id(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_voice_settings(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_model(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_turbo_model(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_list_voices(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_validate_credentials_valid(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_validate_credentials_invalid(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_empty_text_error(elevenlabs_provider):
    """"""
    # This test expects an error
    try:
        result = await elevenlabs_provider.generate_speech(
        )
        # If result exists, check it indicates failure
        if hasattr(result, "success"):
            assert result.success is False
    except Exception:
        pass  # Error is expected


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_missing_api_key_error(elevenlabs_provider):
    """"""
    # This test expects an error
    try:
        result = await elevenlabs_provider.generate_speech(
        )
        # If result exists, check it indicates failure
        if hasattr(result, "success"):
            assert result.success is False
    except Exception:
        pass  # Error is expected


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_output_format(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_initialization_with_defaults(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_provider_name(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_headers_generation(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_long_text_generation(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_basic_generation(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_voice_id(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_voice_settings(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_model(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_turbo_model(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_streaming(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_list_voices(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_validate_credentials_success(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_validate_credentials_failure(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_empty_text_error(elevenlabs_provider):
    """"""
    # This test expects an error
    try:
        result = await elevenlabs_provider.generate_speech(
        )
        # If result exists, check it indicates failure
        if hasattr(result, "success"):
            assert result.success is False
    except Exception:
        pass  # Error is expected


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_missing_api_key_error(elevenlabs_provider):
    """"""
    # This test expects an error
    try:
        result = await elevenlabs_provider.generate_speech(
        )
        # If result exists, check it indicates failure
        if hasattr(result, "success"):
            assert result.success is False
    except Exception:
        pass  # Error is expected


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_initialization_with_defaults(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_initialization_with_custom_settings(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_long_text_generation(elevenlabs_provider):
    """"""
    result = await elevenlabs_provider.generate_speech(
    )
    assert result is not None
    assert result.success is True


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_invalid_voice_id_error(elevenlabs_provider):
    """"""
    # This test expects an error
    try:
        result = await elevenlabs_provider.generate_speech(
        )
        # If result exists, check it indicates failure
        if hasattr(result, "success"):
            assert result.success is False
    except Exception:
        pass  # Error is expected

