"""Integration tests for ImageProvider

These tests make real API calls to the dalle service.
They will be skipped if OPENAI_API_KEY is not set in environment.

Run with: pytest image/test_dalle.py -m live_api -v

Auto-generated by provider onboarding agent.
"""

import os
import pytest
from pathlib import Path
from core.providers.image.dalle import ImageProvider
from core.providers.base import AudioProviderConfig


# Skip all tests in this file if API key not available
pytestmark = pytest.mark.skipif(
    not os.getenv("OPENAI_API_KEY"),
    reason="OPENAI_API_KEY not set - skipping live API tests"
)


@pytest.fixture
def dalle_config():
    """Create dalle provider configuration"""
    api_key = os.getenv("OPENAI_API_KEY")
    return VideoProviderConfig(
        api_key=api_key,
        timeout=60
    )


@pytest.fixture
def dalle_provider(dalle_config):
    """Create dalle provider instance"""
    return ImageProvider(dalle_config)


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_basic_generation_dalle3(dalle_provider):
    """Test basic image generation with DALL-E 3"""
    result = await dalle_provider.generate(
        prompt="A beautiful sunset over mountains",
        model="dall-e-3",
    )

    assert result is not None


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_basic_generation_dalle2(dalle_provider):
    """Test basic image generation with DALL-E 2"""
    result = await dalle_provider.generate(
        prompt="A red apple on a table",
        model="dall-e-2",
    )

    assert result is not None


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_size(dalle_provider):
    """Test image generation with custom size parameter"""
    result = await dalle_provider.generate(
        prompt="A futuristic cityscape",
        model="dall-e-3",
        size="1024x1024",
    )

    assert result is not None


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_quality(dalle_provider):
    """Test DALL-E 3 generation with quality parameter"""
    result = await dalle_provider.generate(
        prompt="A photorealistic cat",
        model="dall-e-3",
        quality="hd",
    )

    assert result is not None


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_generation_with_style(dalle_provider):
    """Test DALL-E 3 generation with style parameter"""
    result = await dalle_provider.generate(
        prompt="A robot playing piano",
        model="dall-e-3",
        style="vivid",
    )

    assert result is not None


@pytest.mark.live_api
def test_get_models(dalle_provider):
    """Test retrieving list of available models"""
    result = dalle_provider.get_models(
    )

    assert result is not None
    assert result is not None


@pytest.mark.live_api
def test_setup_auth_success(dalle_provider):
    """Test successful authentication setup with valid API key"""
    result = dalle_provider.setup_auth(
    )



@pytest.mark.live_api
def test_setup_auth_missing_key(dalle_provider):
    """Test authentication setup fails without API key"""
    result = dalle_provider.setup_auth(
    )



@pytest.mark.live_api
@pytest.mark.asyncio
async def test_error_empty_prompt(dalle_provider):
    """Test error handling for empty prompt"""
    # This test expects an error
    try:
        result = await dalle_provider.generate(
            prompt="",
        )
        # If result exists, check it indicates failure
        if hasattr(result, "success"):
            assert result.success is False
    except Exception:
        pass  # Error is expected


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_error_invalid_model(dalle_provider):
    """Test error handling for invalid model name"""
    # This test expects an error
    try:
        result = await dalle_provider.generate(
            prompt="A painting",
            model="invalid-model",
        )
        # If result exists, check it indicates failure
        if hasattr(result, "success"):
            assert result.success is False
    except Exception:
        pass  # Error is expected


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_error_invalid_size(dalle_provider):
    """Test error handling for invalid size parameter"""
    # This test expects an error
    try:
        result = await dalle_provider.generate(
            prompt="A landscape",
            model="dall-e-3",
            size="invalid-size",
        )
        # If result exists, check it indicates failure
        if hasattr(result, "success"):
            assert result.success is False
    except Exception:
        pass  # Error is expected


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_dalle2_multiple_images(dalle_provider):
    """Test DALL-E 2 generation with multiple images (n parameter)"""
    result = await dalle_provider.generate(
        prompt="A cute dog",
        model="dall-e-2",
        n=2,
    )

    assert result is not None


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_response_format_url(dalle_provider):
    """Test image generation with URL response format"""
    result = await dalle_provider.generate(
        prompt="A blue ocean",
        model="dall-e-2",
        response_format="url",
    )

    assert result is not None


@pytest.mark.live_api
@pytest.mark.asyncio
async def test_response_format_b64_json(dalle_provider):
    """Test image generation with base64 JSON response format"""
    result = await dalle_provider.generate(
        prompt="A green forest",
        model="dall-e-2",
        response_format="b64_json",
    )

    assert result is not None


@pytest.mark.live_api
def test_get_headers(dalle_provider):
    """Test HTTP headers generation for API requests"""
    result = dalle_provider._get_headers(
    )

    assert result is not None
    assert result['Authorization'].startswith('Bearer ')

