"""Unit tests for core/ingest/photos.py.

Exercises the fixtures generated by tests/fixtures/photos/make_fixtures.py — see
that module for the fixture layout and the constants (timestamp, GPS coordinates,
EXIF offsets) asserted against below.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import pytest

from core.ingest.models import LocationSource, TzSource
from core.ingest.photos import (
    camera_key,
    cluster_by_camera,
    load_photos,
    resolve_sidecar,
)

FIXTURES = Path(__file__).parent.parent / "fixtures" / "photos" / "data"

# Kept in sync with tests/fixtures/photos/make_fixtures.py
SIDECAR_UTC = datetime.fromtimestamp(1683191553, tz=timezone.utc)
SIDECAR_LAT = 38.682
SIDECAR_LON = -122.395


def _by_name(photos, name):
    for photo in photos:
        if photo.path.name == name:
            return photo
    raise AssertionError(f"no fixture photo named {name!r} in {[p.path.name for p in photos]}")


# --------------------------------------------------------------------------- #
# resolve_sidecar naming variants
# --------------------------------------------------------------------------- #

class TestResolveSidecar:
    def test_exact_match(self):
        photo = FIXTURES / "sidecars" / "IMG_4471.jpg"
        sidecar = resolve_sidecar(photo)
        assert sidecar == FIXTURES / "sidecars" / "IMG_4471.jpg.json"

    def test_supplemental_metadata_match(self):
        photo = FIXTURES / "sidecars" / "IMG_4472.jpg"
        sidecar = resolve_sidecar(photo)
        assert sidecar == FIXTURES / "sidecars" / "IMG_4472.jpg.supplemental-metadata.json"

    def test_truncated_match(self):
        photo = FIXTURES / "sidecars" / "IMG_4473.jpg"
        sidecar = resolve_sidecar(photo)
        assert sidecar == FIXTURES / "sidecars" / "IMG_4473.jp.json"

    def test_duplicate_suffixed_match(self):
        photo = FIXTURES / "sidecars" / "IMG_4474(1).jpg"
        sidecar = resolve_sidecar(photo)
        assert sidecar == FIXTURES / "sidecars" / "IMG_4474(1).jpg.json"

    def test_case_mismatched_extension_match(self):
        photo = FIXTURES / "sidecars" / "img_4475.heic"
        sidecar = resolve_sidecar(photo)
        assert sidecar == FIXTURES / "sidecars" / "IMG_4475.HEIC.json"

    def test_no_sidecar_returns_none(self):
        photo = FIXTURES / "exif" / "exif_only.jpg"
        assert resolve_sidecar(photo) is None


# --------------------------------------------------------------------------- #
# Sidecar timestamp / geo priority
# --------------------------------------------------------------------------- #

class TestSidecarPriority:
    def test_sidecar_timestamp_is_utc_and_tagged(self):
        photos = load_photos(FIXTURES / "sidecars", include_screenshots=True)
        photo = _by_name(photos, "IMG_4471.jpg")
        assert photo.taken_utc == SIDECAR_UTC
        assert photo.taken_utc.tzinfo is not None
        assert photo.tz_offset_source == TzSource.SIDECAR

    def test_sidecar_geo_populates_lat_lon(self):
        photos = load_photos(FIXTURES / "sidecars", include_screenshots=True)
        photo = _by_name(photos, "IMG_4471.jpg")
        assert photo.lat == pytest.approx(SIDECAR_LAT)
        assert photo.lon == pytest.approx(SIDECAR_LON)
        assert photo.location_source == LocationSource.SIDECAR

    def test_zero_zero_geodata_is_treated_as_absent(self):
        photos = load_photos(FIXTURES / "sidecars", include_screenshots=True)
        photo = _by_name(photos, "IMG_4476_zerogeo.jpg")
        # The sidecar's timestamp is still good even though its geoData is empty.
        assert photo.taken_utc == SIDECAR_UTC
        assert photo.lat is None
        assert photo.lon is None
        assert photo.location_source == LocationSource.NONE

    def test_sidecar_path_is_recorded_on_the_photo(self):
        photos = load_photos(FIXTURES / "sidecars", include_screenshots=True)
        photo = _by_name(photos, "IMG_4471.jpg")
        assert photo.sidecar_path == FIXTURES / "sidecars" / "IMG_4471.jpg.json"


# --------------------------------------------------------------------------- #
# EXIF-only (no sidecar present)
# --------------------------------------------------------------------------- #

class TestExifOnly:
    def test_exif_only_sets_local_naive_leaves_utc_none(self):
        photos = load_photos(FIXTURES / "exif", include_screenshots=True)
        photo = _by_name(photos, "exif_only.jpg")
        assert photo.taken_local_naive == datetime(2023, 6, 15, 14, 30, 0)
        assert photo.taken_local_naive.tzinfo is None
        assert photo.taken_utc is None
        assert photo.tz_offset_source == TzSource.UNKNOWN

    def test_exif_offset_plus_resolves_utc(self):
        photos = load_photos(FIXTURES / "exif", include_screenshots=True)
        photo = _by_name(photos, "exif_offset_plus.jpg")
        # local 14:30 at +02:00 -> 12:30 UTC
        assert photo.taken_utc == datetime(2023, 6, 15, 12, 30, 0, tzinfo=timezone.utc)
        assert photo.tz_offset_source == TzSource.EXIF_OFFSET
        assert photo.tz_offset_minutes == 120

    def test_exif_offset_minus_resolves_utc(self):
        photos = load_photos(FIXTURES / "exif", include_screenshots=True)
        photo = _by_name(photos, "exif_offset_minus.jpg")
        # local 14:30 at -05:00 -> 19:30 UTC
        assert photo.taken_utc == datetime(2023, 6, 15, 19, 30, 0, tzinfo=timezone.utc)
        assert photo.tz_offset_source == TzSource.EXIF_OFFSET
        assert photo.tz_offset_minutes == -300

    def test_gps_south_and_west_are_negative(self):
        photos = load_photos(FIXTURES / "exif", include_screenshots=True)
        photo = _by_name(photos, "gps_south_west.jpg")
        assert photo.exif_lat < 0
        assert photo.exif_lon < 0
        assert photo.exif_lat == pytest.approx(-38.6517, abs=1e-3)
        assert photo.exif_lon == pytest.approx(-122.395, abs=1e-3)

    def test_gps_north_and_east_are_positive(self):
        photos = load_photos(FIXTURES / "exif", include_screenshots=True)
        photo = _by_name(photos, "gps_north_east.jpg")
        assert photo.exif_lat > 0
        assert photo.exif_lon > 0
        assert photo.exif_lat == pytest.approx(38.6517, abs=1e-3)
        assert photo.exif_lon == pytest.approx(122.395, abs=1e-3)

    def test_exif_gps_also_fills_lat_lon_with_exif_source(self):
        photos = load_photos(FIXTURES / "exif", include_screenshots=True)
        photo = _by_name(photos, "gps_north_east.jpg")
        assert photo.lat == photo.exif_lat
        assert photo.lon == photo.exif_lon
        assert photo.location_source == LocationSource.EXIF


# --------------------------------------------------------------------------- #
# camera_key / cluster_by_camera / credits
# --------------------------------------------------------------------------- #

class TestCameraAttribution:
    def test_camera_key_full_fingerprint(self):
        key = camera_key({"Make": "Apple", "Model": "iPhone 14 Pro", "BodySerialNumber": "ABC123"})
        assert key == "Apple/iPhone 14 Pro/ABC123"

    def test_camera_key_missing_serial_is_stable(self):
        key_a = camera_key({"Make": "Apple", "Model": "iPhone 12", "BodySerialNumber": None})
        key_b = camera_key({"Make": "Apple", "Model": "iPhone 12"})
        assert key_a == key_b == "Apple/iPhone 12"

    def test_camera_key_all_absent_is_unknown(self):
        assert camera_key({}) == "unknown"
        assert camera_key({"Make": None, "Model": None, "BodySerialNumber": None}) == "unknown"

    def test_cluster_by_camera_partitions_mixed_folder(self):
        photos = load_photos(FIXTURES / "cameras", include_screenshots=True)
        clusters = cluster_by_camera(photos)

        assert len(clusters["Apple/iPhone 14 Pro/ABC123"]) == 2
        assert len(clusters["Apple/iPhone 12"]) == 2  # no-serial camera still clusters
        assert len(clusters["Canon/EOS R6/XYZ999"]) == 1
        assert len(clusters["unknown"]) == 1

    def test_credited_camera_gets_credit(self):
        photos = load_photos(
            FIXTURES / "cameras",
            include_screenshots=True,
            credits={"Apple/iPhone 14 Pro/ABC123": "Aaron"},
        )
        photo = _by_name(photos, "apple_a.jpg")
        assert photo.credit == "Aaron"

    def test_uncredited_camera_stays_none(self):
        photos = load_photos(
            FIXTURES / "cameras",
            include_screenshots=True,
            credits={"Apple/iPhone 14 Pro/ABC123": "Aaron"},
        )
        canon_photo = _by_name(photos, "canon_a.jpg")
        unknown_photo = _by_name(photos, "no_camera.jpg")
        assert canon_photo.credit is None
        assert unknown_photo.credit is None

    def test_no_credits_mapping_leaves_everyone_uncredited(self):
        photos = load_photos(FIXTURES / "cameras", include_screenshots=True)
        assert all(photo.credit is None for photo in photos)


# --------------------------------------------------------------------------- #
# Screenshot detection
# --------------------------------------------------------------------------- #

class TestScreenshotDetection:
    def test_screenshots_excluded_by_default(self):
        photos = load_photos(FIXTURES / "screenshots")
        names = {p.path.name for p in photos}
        assert "screenshot.jpg" not in names
        assert "not_screenshot.jpg" in names

    def test_screenshots_included_with_flag(self):
        photos = load_photos(FIXTURES / "screenshots", include_screenshots=True)
        screenshot = _by_name(photos, "screenshot.jpg")
        not_screenshot = _by_name(photos, "not_screenshot.jpg")
        assert screenshot.is_screenshot is True
        assert not_screenshot.is_screenshot is False


# --------------------------------------------------------------------------- #
# photo_id stability
# --------------------------------------------------------------------------- #

class TestPhotoId:
    def test_identical_bytes_yield_identical_id(self):
        photos = load_photos(FIXTURES / "hashes", include_screenshots=True)
        original = _by_name(photos, "original.jpg")
        duplicate = _by_name(photos, "duplicate.jpg")
        assert original.photo_id == duplicate.photo_id
        assert original.path != duplicate.path

    def test_different_bytes_yield_different_id(self):
        photos = load_photos(FIXTURES / "hashes", include_screenshots=True)
        original = _by_name(photos, "original.jpg")
        different = _by_name(photos, "different.jpg")
        assert original.photo_id != different.photo_id

    def test_photo_id_is_stable_across_reloads(self):
        first = load_photos(FIXTURES / "hashes", include_screenshots=True)
        second = load_photos(FIXTURES / "hashes", include_screenshots=True)
        first_ids = {p.path.name: p.photo_id for p in first}
        second_ids = {p.path.name: p.photo_id for p in second}
        assert first_ids == second_ids


# --------------------------------------------------------------------------- #
# load_photos general behavior
# --------------------------------------------------------------------------- #

class TestLoadPhotos:
    def test_returns_a_photo_per_image_file(self):
        photos = load_photos(FIXTURES / "sidecars", include_screenshots=True)
        # 6 photo/sidecar pairs live under sidecars/ (json files are not photos)
        assert len(photos) == 6

    def test_ignores_json_sidecar_files_as_photos(self):
        photos = load_photos(FIXTURES / "sidecars", include_screenshots=True)
        assert all(p.path.suffix.lower() != ".json" for p in photos)
